----------------------------------------------------------------------------------------------------------------
-- WASD QWERTY Pro Key Bindings
-- Based on the WASD_DK preset by Dreamkilled, with cross-faction consistency and Shift-queue conflict fixes

-- Bindings use format "Control+Shift+A"

-- Valid keys
	--  a - Z   0 - 9
	-- Backspace Tab Enter Escape Space Apostrophe Comma Minus Period Slash Semicolon Equal LBracket Backslash RBracket Grave 
	-- Up Down Left Right Control Shift Alt CapsLock NumLock ScrollLock Insert Delete Home End PageUp PageDown F1 F2 F3 F4 F5 F6 F7 F8 F9 F10 F11 F12 PrintScreen Pause 
	-- MouseLeft MouseRight MouseMiddle MouseTop MouseBottom 
	-- ScreenLeft ScreenRight ScreenTop ScreenBottom 
	-- Numpad0 Numpad1 Numpad2 Numpad3 Numpad4 Numpad5 Numpad6 Numpad7 Numpad8 Numpad9 NumpadMultiply NumpadPlus NumpadSeparator NumpadMinus NumpadPeriod NumpadSlash 
	
bindings_version = 1.0
bindings_locstring = "WASD_QWERTY_PRO"

bindings =
{
	----------------------------------------------------------------------------------------------------------------
	-- SYSTEM COMMANDS
	----------------------------------------------------------------------------------------------------------------
	escape			= "Tab",
	accept			= "C",
	commandqueue		= "Shift",
	systemmenu		= "Escape",
	objectivesmenu		= "F10",
	alliesmenu		= "F11",
	chatmenu		= "Enter",
	chathistory		= "Shift+H",
	pause			= "F8",
	selectionfocus          = "Apostrophe",
	
	----------------------------------------------------------------------------------------------------------------
	-- TASKBAR COMMANDS
	----------------------------------------------------------------------------------------------------------------
	stop 						= "Control+C",
	move 						= "",
	attackmove					= "Space",
	attackmelee					= "Control+Space",
	build						= "Tab",
	buildadv					= "",
	attach						= "F",
	attackground					= "Shift+Space",
	jump						= "V",
	rally						= "Control+Q",
	combatstance					= "",
	meleestance					= "",
	scuttle						= "Delete",
	infiltrate					= "V",
	unload						= "G",
	deepstrike					= "Control+Z",
	reinforce					= "Q",
	leader						= "E",
	cancelconstruction 				= "B",
	rampage						= "V",
	repair						= "R",
	possess						= "Control+Z", -- chaos daemon
	relocate					= "Control+Z",
	cannibalism					= "V",
	possess_enemy					= "Z", --necron
	fear						= "F",
	tau_snare_trap					= "Shift+Z", -- ork burna bomb
	tau_holographic_projection			= "X",
	direct_spawn					= "Shift+Z", -- tau harbinger drones 21	
	necron_stasis_field				= "Shift+Z",
	entrench					= "Shift+Z",
	burrow						= "Z",
	lightning_field					= "Shift+C", --necron
	direct_spawn_rally				= "R",
	melee_dance					= "Z", -- eldar harlequin
	harvest						= "V", --necron
	
	----------------------------------------------------------------------------------------------------------------
	-- ADVANCED TASKBAR COMMANDS
	----------------------------------------------------------------------------------------------------------------
	hq_cycle					= "Shift+J",
	military_cycle					= "Shift+K",
	builder_cycle					= "Shift+L",
	research_cycle					= "Shift+M",
	cycle_event_cue					= "Y",
	stance_hold					= "F1",
	stance_stand_ground				= "Shift+F",
	stance_burn					= "F3",
	stance_cease_fire				= "F4",
	stance_attack					= "F5",
	melee_stance_assault				= "G",
	melee_stance_ranged				= "Shift+G",
	toggle_taskbar					= "Control+H",
	minimap_ping					= "P",
	minimap_ping_toggle				= "Control+E",
	toggle_overwatch				= "Control+O",
	cancel_overwatch				= "Control+K",
	
	----------------------------------------------------------------------------------------------------------------
	-- MULTIPLE SELECTION HOTKEYS
	----------------------------------------------------------------------------------------------------------------
	focus_primary_selection 	= "Control+Tab",
	next_primary_selection  	= "Tab",
	prev_primary_selection  	= "",
	remove_selection_modifier  	= "Control",		
	crop_selection_modifier  	= "Shift",		
		
	----------------------------------------------------------------------------------------------------------------
	-- DATA CONTEXT HOTKEYS
	----------------------------------------------------------------------------------------------------------------
	
	-- BUILDINGS FOR MARINES
	marine_hq					= 	"Q",
	marine_artefact					=	"C",
	marine_armoury					= 	"Z",
	marine_chapel					=	"E",
	marine_generator				= 	"T",
	marine_listening_post				=	"R",
	marine_orbital_relay				= 	"Shift+C",
	marine_temp_drop_building			=	"C",
	marine_thermo_generator				= 	"V",
	marine_bolter_turret				=	"Shift+Z",
	marine_machine_cult				=	"X",
	marine_mine_field				=	"Shift+X",

	-- BUILDINGS FOR CHAOS 
	chaos_hq					=	"Q",
	chaos_sacrificial_circle			=	"C",
	chaos_armoury					=	"Z",
	chaos_temple					=	"E",
	chaos_generator					=	"T",
	chaos_listening_post				=	"R",
	chaos_greater_circle				=	"Shift+C",
	chaos_thermo_generator				=	"V",
	chaos_bolter_turret				=	"Shift+Z",
	chaos_machine_pit				=	"X",
	chaos_mine_field				=	"Shift+X",

	-- BUILDINGS FOR ORKS
	ork_hq						=	"Q",
	ork_waagh_banner				=	"Z",
	ork_pile_o_guns					=	"X",
	ork_boy_hut					=	"E",
	ork_generator					=	"T",
	ork_listening_post				=	"R",
	ork_big_generator				=	"V",
	ork_mek_shop					=	"C",
	ork_mine_field					=	"Shift+Z",

	-- BUILDINGS FOR ELDAR
	eldar_hq					=	"Q",
	eldar_aspect_portal				=	"E",
	eldar_soul_shrine				=	"X",
	eldar_webway_gate				=	"Z",
	eldar_generator					=	"T",
	eldar_listening_post				=	"R",
	eldar_advanced_generator			=	"V",
	eldar_support_platform				=	"Shift+Z",
	eldar_support_portal				=	"C",
	eldar_mine_field				=	"Shift+X",

	-- BUILDINGS FOR TAU
	tau_barracks					=	"E",
	tau_hq						=	"Q",
	tau_kroot_nest					=	"Z",
	tau_listening_post				=	"R",
	tau_plasma_generator				=	"T",
	tau_research_building				=	"X",
	tau_shrine_of_kauyon				=	"Shift+X",
	tau_shrine_of_montka				=	"Shift+Z",
	tau_shrine_of_purpose				=	"Shift+C",
	tau_thermo_generator				= 	"V",
	tau_vehicle_building				= 	"C",

	-- BUILDINGS FOR NECRONS
	necron_energy_core				=	"Shift+C",
	necron_forbidden_archive			=	"X",
	necron_greater_summoning_core			=       "C",
	necron_listening_post				=	"R",
	necron_monolith					=	"Q",
	necron_plasma_generator				=	"T",
	necron_summoning_core				=	"Z",
	necron_thermo_generator				=       "V",
	necron_turret					=	"Shift+Z",
	
    	-- BUILDINGS FOR IMPERIAL GUARD
	guard_hq						= "Q",
	guard_tactica						= "Z",
	guard_infantry						= "E",
	guard_generator					 	= "T",
	guard_listening_post					= "R",
	guard_mars_command					= "C",
	guard_thermo_generator					= "V",
	guard_bolter_turret					= "Shift+Z",
	guard_mechanized_command 				= "X",
	guard_mine_field 					= "Shift+X",
	
	-- BUILDINGS FOR DARK ELDAR
	dark_eldar_hq						= "Q",
	dark_eldar_haemonculus_laboratory			= "C",
	dark_eldar_hall_of_blood				= "E",
	dark_eldar_dark_foundry					= "X",
	dark_eldar_generator					= "T",
	dark_eldar_listening_post				= "R",
	dark_eldar_slave_caravel				= "Z",
	dark_eldar_soul_cage					= "Shift+X",
	dark_eldar_thermo_generator				= "V",
	dark_eldar_wych_cult_arena				= "Shift+Z",

	-- BUILDINGS FOR SISTERS
	sisters_hq						= "Q",
	sisters_infantry					= "E",
	sisters_sanctuary					= "Z",
	sisters_generator					= "T",
	sisters_thermo_generator				= "V",
	sisters_listening_post					= "R",
	sisters_vehicle_building				= "X",
	sisters_turret_flamer					= "Shift+C",
	sisters_holy_reliquary					= "C",
	sisters_shrine						= "Shift+Z",
	sisters_mines						= "Shift+X",

	-- TROOPERS FOR MARINES
	marine_servitor						= "Q",
	marine_dreadnought					= "R",
	marine_dreadnought_hellfire				= "T",
	marine_force_commander					= "Z",
	marine_chaplain						= "R",
	marine_grey_knights					= "X",
	marine_land_speeder					= "E",
	marine_librarian					= "E",
	marine_skull_probe					= "Shift+Z",
	marine_scout						= "E",
	marine_apothecary					= "Q",
	marine_assault_marine					= "E",
	marine_sergeant						= "G",
	marine_space_marine					= "Q",
	marine_terminator					= "R",
	marine_assault_terminator				= "T",	
	marine_land_raider					= "V",
	marine_predator						= "C",
	marine_rhino						= "Q",
	marine_whirlwind					= "X",
	marine_techmarine					= "O", 
	marine_tempest						= "Z",

	-- TROOPERS FOR CHAOS
	chaos_bloodthirster					= "E",
	chaos_cultist						= "E",
	chaos_daemon_prince					= "",
	chaos_defiler						= "E",
	chaos_horrors						= "Q",
	chaos_lord						= "Z",
	chaos_marines						= "Q",
	chaos_raptors						= "E",
	chaos_possessed						= "E",
	chaos_obliterator					= "Q",
	chaos_predator						= "R",
	chaos_aspiring_champion					= "Z",
	chaos_rhino						= "Q",
	chaos_heretic						= "Q",
	chaos_sorcerer						= "R",
	chaos_khorne_berserker					= "R",
	chaos_dreadnought					= "O", 
	chaos_hell_talon					= "T",


	-- TROOPERS FOR ORKS
	ork_flash_gitz						= "X",
	ork_nobs						= "R",
	ork_shoota_boyz						= "E",
	ork_slugga_boyz						= "Q",
	ork_stormboyz						= "R",
	ork_tankbustas						= "V",
	ork_grots						= "E",
	ork_killa_kan						= "R",
	ork_bad_dok						= "R",
	ork_mek_boy						= "Z",
	ork_nob_leader						= "L",
	ork_warboss						= "T",
	ork_looted_tank						= "Z",
	ork_squiggoth						= "X",
	ork_trukk						= "Q",	
	ork_wartrak						= "E",
	ork_armored_nob						= "V",
	ork_gun_wagon						= "O", 
	ork_fighta_bomma					= "T",
	
	-- TROOPERS FOR ELDAR
	eldar_bonesinger					= "Q",
	eldar_grav_platform_laser				= "Q",
	eldar_grav_platform_brightlance				= "E",
	eldar_avatar						= "X",
	eldar_farseer						= "Z",
	eldar_harlequin						= "T",
	eldar_warlock						= "E",
	eldar_warlock_seer					= "R",
	eldar_falcon_grav_tank					= "Q",
	eldar_fire_prism					= "T",
	eldar_vyper						= "E",
	eldar_wraithlord					= "R",
	eldar_banshee						= "E",
	eldar_banshee_exarch					= "H",
	eldar_dark_reapers					= "R",	
	eldar_dark_reaper_exarch				= "",
	eldar_guardians						= "E",
	eldar_rangers						= "Q",
	eldar_warp_spiders					= "T",		
	eldar_warp_spiders_exarch				= "E",		
	eldar_fire_dragon					= "V",	
	eldar_wraithguard					= "O", 
	eldar_nightwing						= "Z",


	-- TROOPERS FOR TAU
	tau_attack_drone					= "Z",
	tau_broadside_battlesuit				= "T",
	tau_builder						= "Q",
	tau_centaur_auxiliary					= "C",
	tau_commander						= "Z",
	tau_crisis_suit						= "X",
	tau_devilfish_carrier					= "Q",
	tau_drone_harbinger					= "T",
	tau_drone_squad						= "E",
	tau_energy_auxiliary					= "Z",
	tau_eradicator						= "R",
	tau_eradicator_kroot					= "",
	tau_ethereal						= "Q",
	tau_eviscerator						= "V",
	tau_eviscerator_kroot					= "C",
	tau_fire_warrior					= "Q",
	tau_fire_warrior_shasui					= "Shift+Z",
	tau_fire_warrior_shield_drone				= "Shift+X",
	tau_commander_sp_drone			= "C", -- find
	tau_glob_auxiliary					= "G",
	tau_greater_knarloc					= "T",
	tau_hammerhead						= "Z",
	tau_kroot_hound						= "E",
	tau_kroot_shaper					= "Q",
	tau_kroot_warrior					= "E",
	tau_krootox						= "R",
	tau_pathfinder						= "R",
	tau_skyray						= "R",
	tau_stealth_warrior					= "E",
	tau_vespid_auxiliary					= "R",
	tau_piranha						= "O", 
	tau_barracuda						= "Z",
	
	-- TROOPERS FOR NECRONS
	necron_attack_scarab					= "E",
	necron_builder_scarab					= "Q",
	necron_destroyer					= "Shift+X",
	necron_flayed_one					= "X",
	necron_heavy_destroyer					= "Shift+C",
	necron_immortal						= "Z",	
	necron_lord						= "T",
	necron_lord_destroyer					= "Shift+V",
	necron_pariah						= "C",
	necron_restored_monolith				= "Shift+Z",
	necron_tomb_spyder					= "V",
	necron_warrior						= "E",
	necron_wraith						= "R",
	necron_deceiver						= "O",

	-- TROOPERS FOR IMPERIAL GUARD
	guard_enginseer						= "E",
	guard_guardsmen				    		= "Q",
	guard_heavy_weapon          				= "E",
	guard_command_squad					= "Z",
	guard_commissar						= "Z",
	guard_priest						= "C",
   	guard_psyker						= "X",
	guard_kasrkin						= "R",
	guard_ogryn						= "T",
	guard_basilisk						= "T",
	guard_sentinel						= "E",
	guard_hellhound						= "R",
	guard_assassin						= "V",
	guard_baneblade						= "Q",
	guard_leman_russ					= "X",
	guard_chimera						= "Q",
	guard_sergeant						= "Z",
	guard_demolisher					= "C",
	guard_marauder						= "Z",

	
	-- TROOPERS FOR DARK ELDAR
	dark_eldar_slave					= 	"Q",
	dark_eldar_mandrake					=	"E",
	dark_eldar_archon					=	"Q",
	dark_eldar_incubus					=	"Z",
	dark_eldar_warrior					=	"E",
	dark_eldar_hellion					=	"Q",
	dark_eldar_scourge					=	"R",
	dark_eldar_warp_beast					=	"Z",
	dark_eldar_wych						=	"T",
	dark_eldar_haemonculus					=	"R",
	dark_eldar_reaver					=	"E",
	dark_eldar_raider					=	"R",
	dark_eldar_talos					=	"Z",
	dark_eldar_ravager					=	"X",
	dark_eldar_dais						=	"C",
	dark_eldar_squad_leader					=	"O",
	dark_eldar_murdered_slave				=	"O",
	dark_eldar_raven					=	"T",


	-- TROOPERS FOR SISTERS
	sisters_servitor					=	"Q",
	sisters_battle_sister					=	"E",
	sisters_seraphim					=	"R",
	sisters_repentia					=	"X",
	sisters_celestian					=	"T",
	sisters_missionary					=	"E",
	sisters_assassin					=	"Z",
	sisters_canoness					=	"Q",
	sisters_confessor					=	"R",
	sisters_celestian_imagifer				=	"X",
	sisters_repentia_mistress				=	"E",
	sisters_veteran_superior				=	"E",
	sisters_veteran_superior_celestian			=	"Z",
	sisters_veteran_superior_seraphim			=	"Control+W",
	sisters_living_saint					=	"Q",
	sisters_exorcist_tank					=	"T",
	sisters_immolator_tank					=	"E",
	sisters_penitent_engine					=	"Z",
	sisters_rhino						=	"Q",
	sisters_lightning					=	"R",

	-- WEAPON UPGRADES FOR MARINES
	marine_assault_cannon					=	"Z",
	marine_flamer						=	"Z",
	marine_heavy_flamer					=	"Z",
	marine_heavy_bolter					=	"X",
	marine_lascannon_1					=	"X",
	marine_lascannon_2					=	"X",
	marine_lascannon_twin					=	"X",
	marine_missile_launcher					=	"Control+X",
	marine_plasma_gun					=	"Control+Z",
	marine_sniper_rifle					=	"Control+V",
	marine_missile_launcher_turret 				= "Q",
	marine_power_halberd					= "V",
	marine_missile_frag					= "Z",
	marine_missile_krak					= "X",


	-- WEAPON UPGRADES FOR CHAOS 	
	chaos_flamer						=	"Z",
	chaos_heavy_flamer					=	"Z",
	chaos_grenade_launcher					=	"Z",
	chaos_heavy_bolter					=	"Z",
	chaos_lascannon_1					=	"X",
	chaos_lascannon_2					=	"Control+Z",
	chaos_lascannon_twin					=	"Z",
	chaos_missile_launcher					=	"Control+X",
	chaos_plasma_gun					=	"X",
	chaos_missile_launcher_turret				= "Q",
	chaos_multi_melta					=	"M",

	-- WEAPON UPGRADES FOR ORKS
	ork_big_shoota						=	"Z",
	ork_kustom_shoota					=	"X",
	ork_bomb_chucka						=	"X",
	ork_burna						=	"Z",
	ork_mega_blasta						=	"M",
	ork_power_klaw						=	"Z",
	ork_rokkit_launcha					=	"Z",
	ork_rokkit_launcha_twin					=	"X",
	ork_shoota						=	"X",
	ork_zzzap_gun						=	"V",
		
	-- WEAPON UPGRADES FOR GUARD
	guard_grenade_launcher					=	"Z",
	guard_plasma_gun					=	"X",
	guard_lasgun_heavy_weapons_team 			=	"Z",
	guard_autocannon_heavy_weapons_team			=	"X",
	guard_multi_melta					=	"M",
	guard_multi_laser_sentinel				=	"M",
	guard_autocannon_sentinel				=	"C",

	-- WEAPON UPGRADES FOR ELDAR
	eldar_bright_lance					=	"Z",
	eldar_dcannon						=	"Q",
	eldar_missile_launcher					=	"Z",
	eldar_scatter_laser					=	"X",
	eldar_shuriken_cannon					=	"X",
	eldar_starcannon					=	"Z",
	eldar_witchblade_seercouncil				= "Z",

	-- WEAPON UPGRADES FOR TAU
	tau_flamer_commander					=	"Z",
	tau_missile_launcher_commander				=	"E",
	tau_plasma_rifle_commander				=	"Q",
	tau_missile_launcher_crisis_suit			=  "Z",
	tau_flamer_crisis_suit					=  "X",
	tau_stealth_suit_fusion_blaster				=  "Z",
	
	-- WEAPON UPGRADES FOR NECRONS	
	necron_tomb_spyder_particle_projector		= "Z",
	
	-- WEAPON UPGRADES FOR DARK ELDAR
	dark_eldar_darklance_raider		=	"O", 
	dark_eldar_darklance_scourge		=	"Z",
	dark_eldar_disintegrator_ravager	=	"Z",

	--WEAPON UPGRADES FOR SISTERS
	sisters_flamer				=	"Z",
	sisters_heavy_bolter			=	"X",
	sisters_chainsword			=	"C", 
	sisters_multi_melta			=	"Control+X",
	sisters_meltagun			=	"Control+Z",

	-- RESEARCH FOR MARINES
	marine_accuracy_research_1		=	"X",
	marine_accuracy_research_2		=	"X",
	marine_force_commander_research_1	=	"Shift+Z",
	marine_force_commander_research_2	=	"Shift+Z",
	marine_daemon_hammer_research		=	"",
	marine_frag_grenade_research		=	"Shift+Z",
	marine_health_research_1		=	"Z",
	marine_health_research_2		=	"Z",
   	marine_commander_health_research_1	=	"Z",
	marine_commander_health_research_2	=	"Z",
	marine_librarian_research_1		=	"Shift+X",
	marine_librarian_research_2		=	"X",
	marine_max_weapons_research		=	"Q",
	marine_melta_bomb_research		=	"V",
	marine_power_research_1			=	"Q",
	marine_power_research_2			=	"Q",	
	marine_requisition_research_1		=	"Q",
	marine_requisition_research_2		=	"Q",
	marine_scout_infiltration_research	=	"Shift+C",
	marine_sniper_rifle_research			=	"Shift+V",
	marine_smoke_launcher_research		=	"H",		
	marine_squad_cap_research		=	"Z",		
	marine_vehicle_cap_research		=	"X",
	marine__melee_research_1		=	"O",
	marine_sergeant_melee_research_2	=	"Shift+Z",		
	marine_sergeant_ranged_research		=	"Shift+X",
	marine_personalteleporter_research	=	"Z",
	marine_heavy_armor_deployment		=	"Shift+Z",
	marine_furious_charge_research		=	"E",
	marine_power_swords_research		= 	"Shift+Z",
	marine_skull_probe_infiltration_research	= "Shift+X",
	
	-- RESEARCH FOR CHAOS
	chaos_purge_the_weak			=	"R",
	chaos_ranged_research_1			=	"R",
	chaos_cultist_sight_research		=	"Shift+V",
	chaos_lord_research_1			=	"Shift+X",
	chaos_lord_research_2			=	"Shift+X",
	chaos_frag_grenade_research		=	"V",
	chaos_health_research_1			=	"X",
	chaos_health_research_2			=	"X",
	chaos_commander_health_research_1	=	"Shift+Z",
	chaos_commander_health_research_2	=	"Shift+Z",
	chaos_sorcerer_research_1		=	"Shift+C",
	chaos_sorcerer_research_2		=	"Shift+C",
	chaos_max_weapons_research		=	"Z",
	chaos_power_research_1			=	"Q",
	chaos_power_research_2			=	"Q",	
	chaos_requisition_research_1		=	"Q",
	chaos_requisition_research_2		=	"Q",
	chaos_infiltration_research		=	"Shift+C",
	chaos_marine_infiltration_research	=	"Shift+V",
	chaos_smoke_launcher_research		=	"X",		
	chaos_squad_cap_research		=	"Z",		
	chaos_vehicle_cap_research		=	"X",		
	chaos_champion_melee_research_1		=	"Shift+Z",
	chaos_champion_melee_research_2		=	"Shift+Z",		
	chaos_champion_ranged_research		=	"Shift+X",	
	chaos_furious_charge_research		=	"Q",	
	chaos_raptor_speed_research		=	"Shift+X",
	chaos_accuracy_upgrade_research_1	=	"Z",
	chaos_accuracy_upgrade_research_2	=	"Z",
	chaos_personalteleporters		=	"Z",
	chaos_possessed_daemon_fire_research 	= "Z",
	chaos_possessed_daemon_flight_research 	= "X",
	chaos_possessed_daemon_mutation_research = "Z",
	chaos_possessed_daemon_talons_research 	= "V",
	chaos_projectiles			= "Z",
	chaos_rage_research				=  "V",
	chaos_bloodthirster_research			= "E",
	chaos_daemon_prince_research			= "R",


	-- RESEARCH FOR ORKS
	ork_big_squad_research				=	"B",
	ork_big_shoota_research				=	"E",
	ork_burna_research				=	"R",
	ork_eavy_armour_research			=	"Shift+Z",
	ork_extra_armour_research			=	"Shift+Z",
	ork_mega_blasta_research			=	"M",
	ork_mekboy_melee_research			=	"M",
	ork_mekboy_ranged_research			=	"T",
	ork_morechoppy_research_1			=	"Z",
	ork_morechoppy_research_2			=	"Z",
	ork_moredakka_research_1			=	"Q",
	ork_moredakka_research_2			=	"Q",
	ork_moreshooty_research_1			=	"E",
	ork_moreshooty_research_2			=	"E",
	ork_powerclaw_research				=	"X",	
	ork_rokkit_research				=	"R",
	ork_tougherorks_research_1			=	"T",
	ork_tougherorks_research_2			=	"T",
	ork_warboss_ranged_research			=	"T",		
	ork_tougherbosses_research_1			=	"Shift+X",
	ork_tougherbosses_research_2			=	"Shift+X",
	ork_kustom_force_field_research			=	"Shift+Z",
	ork_tankbustin_kit_research			=	"C",
	ork_kustom_tellyporta_research			=	"Z",
	ork_eavy_armor_boyz_research			=	"Shift+Z",
	ork_speed_boost_research			=	"Shift+X",
	ork_speed_boost_stormboyz_research		=	"Shift+V",
	ork_waaaaagh_research				=	"E",
	ork_research_stikk_bombs			=	"",
	ork_power_research_1				=	"Q",
	ork_power_research_2				=	"Q",
	ork_requisition_research_1			=	"Q",
	ork_requisition_research_2			=	"Q",
	ork_research_grot_infiltration 			= "Z",
	ork_research_tankbustabombs 			= "V",
	ork_research_more_sluggas			= "Shift+C",
	ork_tankbusta_infiltration_research		= "X",

	-- RESEARCH FOR ELDAR
	eldar_ability_research			= "T",
	eldar_accuracy_research			= "E",
	eldar_exarch_ability_research_1		= "Shift+Z",
	eldar_exarch_ability_research_2		= "C",
	eldar_farseer_ability_research_1	= "Z",
	eldar_farseer_ability_research_2	= "X",
	eldar_farseer_ability_research_3	= "X",
	eldar_health_research			= "H",
	eldar_vehicle_ability_research		= "c",
	eldar_warlock_ability_research_1	= "Z",
	eldar_warlock_ability_research_2	= "E",
	eldar_warlock_ability_research_3	= "Z",
	eldar_shroud_ability_research		= "C",
	eldar_fleet_of_foot_research 		= "F",
	eldar_bonesinger_ability_research_3 	= "Shift+X",
	eldar_ranger_infiltration_research 	= "Shift+Z",
	eldar_haywire_grenade_research 		= "Shift+V",
	webway_gate_healing_research 	= "Z",
	eldar_webway_gate_relocation_research 	= "X",
	eldar_plasma_grenade_research 		= "X",
	eldar_bonesinger_ability_research_1 	= "Z",
	eldar_power_research_1 			= "Q",
	eldar_power_research_2 			= "Q",
	eldar_requisition_research_1 		= "Q",
	eldar_requisition_research_2 		= "Q",
	eldar_tier2_research 			= "Shift+Z",
	eldar_research_farseerhealth_1 		= "Shift+V",
	eldar_research_farseerhealth_2 		= "Shift+V",
	eldar_research_infantryaccuracy_1 	= "Shift+X",
	eldar_research_infantryaccuracy_2 	= "Shift+X",
	eldar_researchinfantryhealth_1 		= "Shift+C",
	eldar_researchinfantryhealth_2 		= "Shift+C",
	eldar_annihilate_the_enemy 		= "Q",
	eldar_nightwing_regen_research 		= "Shift+X",
        eldar_vehicle_ability_research		= "Shift+Z",

	-- RESEARCH FOR TAU
	tau_power_research_1			=	"Q",
	tau_power_research_2			=	"Q",
	tau_requisition_research_1		=	"Q",
	tau_requisition_research_2		=	"Q",
	tau_teachings_of_kauyon			=	"Q",
	tau_teachings_of_montka			=	"Q",
	tau_target_lock				=	"Q",
	tau_advanced_pulse_rifles		=  "E",
	tau_improved_metallurgy			=  "R",
	tau_targeting_optics			= 	"T",
	tau_missile_barrage_research					= 	"Z",
	tau_feral_leap				=	"X",
	tau_jetpacks				=  "Z",
	tau_burst_cannon_enhancements		= "X",
	
	
	-- RESEARCH FOR NECRONS
	necron_power_research_1				=	"Q",
	necron_power_research_2				=	"Q",
	necron_chronometron_research			=	"T",
	necron_lightning_field_research			=	"R",
	necron_nightmare_shroud_research		=	"V",
	necron_phase_shifter_research			=	"Z",
	necron_phalactery_research			=	"Z",
	necron_resurrection_orb_research		=	"X",
	necron_solar_pulse_research			=	"C",
	necron_veil_of_darkness_research		=	"C",
	necron_wraith_flight_research			=	"E",
	necron_warrior_disruption_field_research	=	"Q",
	necron_nightbringer_research			=	"Q",
	necron_deceiver_research			=	"O",
	necron_ctan_research				=	"Q",
	
	
	-- RESEARCH FOR GUARD
	guard_guardsman_morale				=	"Q",
	guard_guardsman_morale_2			=	"X",
	guard_research_command_squad_size		=	"R",
	guard_research_kasrkin_armor			=	"Shift+X",
	guard_research_kasrkin_speed			=	"Shift+Z",
	guard_upgrade_guardsmen_health			=	"E",
	guard_upgrade_guardsmen_range			=	"Z",
	guard_upgrade_ogryn_melee			=	"Shift+C",
	guard_upgrade_power_1				=	"Q",
	guard_upgrade_power_2				=	"Q",
	guard_upgrade_requisition_1			=	"Q",
	guard_upgrade_requisition_2			=	"Q",
	guard_upgrade_weapon_specialization		=  "V",
	guard_full_scale_war 				=  "Shift+Z",
	guard_research_sentinel_armor			=	"O",
	guard_research_assassin_infiltrate		=	"Shift+V",
	
-- RESEARCH FOR DARK ELDAR
	dark_eldar_research_crucible				=	"X",
	dark_eldar_research_gruesome_display			=	"Q",
	dark_eldar_research_infiltration_mandrake		=	"Shift+Z",
	dark_eldar_research_short_circuit			=	"Z", 
	dark_eldar_research_soulharvest				=	"V", 
	dark_eldar_research_terrorfex_grenade			=	"C",
	dark_eldar_research_scythes				=	"O",
	dark_eldar_research_poisoned_blades			=	"Shift+Z",
	dark_eldar_research_soul_destruction			=	"V",
	dark_eldar_research_talisman_of_petrification		=	"O",
	dark_eldar_research_barbed_walls			=	"O",
	dark_eldar_research_daemonic_touch			=	"Z",
	dark_eldar_research_range_increase			=	"O",
	dark_eldar_research_wildfire				=	"R",
	dark_eldar_research_reaver_targeting			=	"Shift+X",
	dark_eldar_research_stinger			=	"X",
	dark_eldar_upgrade_power_1				=	"Q",
	dark_eldar_upgrade_power_2				=	"Q",
	dark_eldar_upgrade_requisition_1			=	"Q",
	dark_eldar_upgrade_requisition_2			=	"Q",
	dark_eldar_upgrade_soulseeker				=	"Shift+X",
	dark_eldar_upgrade_power_scythe				=	"V",
	dark_eldar_upgrade_agonizer				=	"V",
	dark_eldar_upgrade_vehicle_armor			=	"Shift+Z",			
	dark_eldar_upgrade_destructor				=	"C",
	dark_eldar_upgrade_commander_health			=	"Shift+Z",
	dark_eldar_upgrade_retinue				=	"Q",
	dark_eldar_upgrade_infantry_health			=	"X",


	-- RESEARCH FOR SISTERS
	sisters_research_martyrs_gift				=	"Z",
	sisters_research_lay_hands				=	"I",
	sisters_research_faithful_morale			=	"X",
	sisters_research_phosphor_grenades			=	"C",
	sisters_research_krak_grenades				=	"C",
	sisters_research_laud_hailer				=	"N",
	sisters_research_max_weapons				=	"Q",
	sisters_research_zealot_charge				=	"E",
	sisters_research_health					=	"Z",
	sisters_research_ranged_damage				=	"X",
	sisters_research_leader_melee_1				=	"Shift+Z",
	sisters_research_leader_melee_2				=	"Shift+Z",
	sisters_research_blessed_ammunition			=	"T",
	sisters_research_leader_range				=	"Shift+X",
	sisters_research_vehicle_armor				=	"V",
	sisters_research_holy_promethium			=	"Shift+C",
	sisters_research_commander_health_1			=	"Q",
	sisters_research_commander_health_2			=	"Q",
	sisters_research_ascension				=	"R",
	sisters_research_battle_standard			=	"X",
	sisters_research_divine_pronouncement			=	"E",
	sisters_research_conflagration				=	"G",
	sisters_research_emperors_touch				=	"J",
	sisters_research_divine_retribution			=	"F",
	sisters_upgrade_power_1					=	"Q",
	sisters_upgrade_power_2					=	"Q",
	sisters_upgrade_requisition_1				=	"Q",
	sisters_upgrade_requisition_2				=	"Q",
	sisters_upgrade_heart_of_worship			=	"X",
	sisters_improved_field_logistics_research		=	"Shift+Z",
	sisters_squad_cap                    	=   	"Shift+Z",
  	sisters_vehicle_cap                     =    	"Shift+X",
	
	-- ADDONS FOR MARINES
	marine_hq_addon_1					=	"Shift+Z",
	marine_hq_addon_2					=	"Shift+Z",
	marine_listening_post_1					=	"Q",
	marine_listening_post_2					=	"Q",
	marine_turret_addon					=	"Q",
	
	-- ADDONS FOR CHAOS
	chaos_hq_addon_1					=	"Shift+Z",
	chaos_hq_addon_2					=	"Shift+Z",
	chaos_listening_post_1					=	"Q",
	chaos_listening_post_2					=	"Q",
	chaos_turret_addon					=	"Q",
		
	-- ADDONS FOR ELDAR
	eldar_banshee_aspect_stone				=	"E",
	eldar_dark_reaper_aspect_stone				=	"R",
	eldar_fire_prism_aspect_stone				=	"T",
	eldar_fire_dragon_aspect_stone				=	"V",
	eldar_vyper_aspect_stone				=	"E",
	eldar_warp_spider_aspect_stone				=	"T",
	eldar_wraithlord_aspect_stone				=	"R",
	eldar_support_platform_addon				=	"Q",
	eldar_listening_post_1					=	"Q",
	eldar_listening_post_2					=	"Q",
	eldar_wraithguard_aspect_stone				=  "T",

	-- ADDONS FOR TAU
	addon_tau_hq_1						=	"C",
	addon_tau_list_post_1					=	"Q",
	addon_tau_list_post_2					=	"Q",

	-- ADDONS FOR NECRONS
	addon_necron_turret					=	"Q",
	addon_necron_list_post_1				=	"Q",
	addon_necron_list_post_2				=	"Q",
	addon_necron_hq_1					=	"Shift+Z",
	addon_necron_hq_2					=	"Shift+Z",
	
	-- ADDONS FOR ORKS
	ork_hq_addon						=	"Shift+Z",
	ork_waagh_banner_gunz_1					=	"Q",
	ork_waagh_banner_gunz_2					=	"Q",
	ork_waagh_banner_orkcap					=	"U",
	ork_waagh_banner_popgrowth				=	"U",
	ork_waagh_banner_supportgrowth				=	"U",	
	ork_listening_post_1					=	"Q",
	ork_listening_post_2					=	"E",

	-- ADDONS FOR IMPERIAL GUARD
	addon_guard_basilisk_depot				=	"T",
	addon_guard_heavy_weapon_vault				=	"H",
	addon_guard_hellhound_depot				=	"R",
	addon_guard_hq_1					=	"Shift+Z",
	addon_guard_hq_2					=  "Shift+Z",
	addon_guard_kasrkin_quarters				=	"R",
	addon_guard_leman_russ_depot				=	"X",
	addon_guard_list_post_1					=	"Q",
	addon_guard_list_post_2					=	"Q",
	addon_guard_ministorum_temple				=  "C",
	addon_guard_ogryn_quarters				=  "T",
	addon_guard_sentinel_depot				=  "E",
	addon_guard_telepathica_temple				=  "X",
	addon_guard_vindicare_temple				=  "V",
	guard_turret_addon					=	"Q",
	addon_guard_demolisher_depot				=  "O",

-- ADDONS FOR DARK ELDAR
	addon_dark_eldar_list_post_1		=	"Q",
	addon_dark_eldar_list_post_2		=	"Q",
	addon_dark_eldar_piercing_vision	=	"I",
	addon_dark_eldar_rend_soul		=	"R",
	addon_dark_eldar_sadism			=	"Z",
	addon_dark_eldar_penumbra		=	"T",
	addon_dark_eldar_nights_veil		=	"Z",
	addon_dark_eldar_screams_of_the_damned	=	"X",
	addon_dark_eldar_sudden_strike		=	"U",
	addon_dark_eldar_slave_graveyard	=	"E",
	addon_dark_eldar_hq_upgrade		=	"Shift+Z",
	addon_dark_eldar_list_post_dark_lance	=	"R",


	-- ADDONS FOR SISTERS
	addon_sisters_list_post_1		=	"Q",
	addon_sisters_list_post_2		=	"Q",
	addon_sisters_holy_icon			=	"Shift+Z",
	addon_sisters_hq_1			=	"Shift+Z",
	addon_sisters_hq_2			=	"Shift+Z",
	addon_sisters_turret			=	"Q",
	
	-- ABILITIES FOR MARINES
	marine_battlecry			=	"B",
	marine_demoralize			=	"G",	
	marine_frag_grenades			=	"X",
	marine_machine_spirit			=	"z",
	marine_melta_bombs			=	"V",
	marine_orbital_bombardment		=	"T",
	marine_rally				=	"E",	
	marine_sabotage				=	"I",
	marine_smite				=	"R",
	marine_smoke_launchers			=	"H",	
	marine_weaken_resolve			=	"F",
	marine_word_of_emperer			=	"C",
	marine_inquisition			=       "Z",
	marine_blessing_of_the_omnissiah	=       "O",
	
	-- ABILITIES FOR CHAOS
	chaos_chains				=	"G",
	chaos_corruption			=	"C",
	chaos_daemon_strength			=	"E",
	chaos_daemon_roar			=       "Z",
	chaos_doom_bolt				=	"R",
	chaos_force_labor			=	"Z",
	chaos_frag_grenades			=	"V",	
	chaos_furious_rage			=	"T",
	chaos_smoke_launchers			=	"X",
	chaos_speed_fiends			=	"F",
	chaos_tainted_auspex			=       "C",
	chaos_rage				=       "V",
	chaos_blood_rage			=       "O",
	chaos_biotoxin				=       "Z",

	-- ABILITIES FOR ELDAR
	eldar_bonesong				=	"Z",
	eldar_eldritch_storm			=	"T",
	eldar_psychic_storm			=	"G",
	eldar_embolden				=	"H",
	eldar_entanglement			=	"I",
	eldar_fleetoffoot			=	"F",	
	eldar_fortune				=	"V",
	eldar_graviticboost			=	"Z",
	eldar_haywire_bombs			=	"Z",
	eldar_guide				=	"E",
	eldar_mind_war				=	"R",
	eldar_plasma_grenades			=	"X",
	eldar_warshout				=	"X",
	eldar_wraithtomb			=	"C",	
	eldar_shroud_ability			=	"C",
	eldar_harlequin_kiss			=       "B",
	eldar_soulstone				=	"O",

	-- ABILITIES FOR TAU
	tau_devour				=	"X",
	tau_hamstring				=	"X",
	tau_sonic_pulse				=	"Z",
	tau_target_acquired			=	"E",
	tau_mark_squad	        	        =  	"Z",
	tau_emp_grenade				= 	"F",
	tau_photon_grenade		        = 	"Z",
	tau_missile_barrage			=       "Z",
	tau_canabalism				=       "V",
	tau_entrench				=       "X",
	tau_ion_shield				=       "X",

	-- ABILITIES FOR NECRONS
	necron_nightmare_shroud			=	 "V", -- mark of khorne
	necron_phase_shifter			=	 "Z",
	necron_solar_pulse			=	 "C",
	necron_doom				=        "Z",
	necron_chronometron			=  "T",
	necron_mass_resurrection  		=  "R",
	necron_deceive			= "X",
	necron_grand_illusion		= "Z",
	necron_misdirect		= "O",
	necron_possess_nightbringer	= "E",
	necron_possess_deceiver		= "F",
	
	-- ABILITIES FOR ORKS
	ork_fightabomba_strafe		=	"Z",
	ork_fightin_juice		=	"C",
	ork_gimme_boyz_mek		=	"M",
	ork_gimme_boyz_warboss		=	"E",
	ork_pop_growth			=	"R",
	ork_power_of_waagh		=	"T",	
	ork_stikkbombs			=	"X",
	ork_tankbusta_bombs		=	"V",
	ork_superstik_bomb		= 	"G",
	ork_turbo_boost			=	"Z",
	ork_waaaaagh			=	"E",
	ork_tank_zzappa			= 	"F",
	ork_power_surge 		= 	"Z",

	-- ABILITIES FOR IMPERIAL GUARD
	guard_assassin_assassinate	=	"Z",
	earthshaker_round		=	"Z",
	guard_commissar_execute		=	"C",
	guard_kasrkin_frag_grenades	=	"F",
	guard_priest_fanatical		=	"C",
	guard_psyker_lighting_arc	=	"E",	
	guard_psyker_strip_soul		=	"R",
	guard_strafing_run		=	"Z",
	guard_let_it_burn		=  	"C",
	guard_long_range_scanner	= 	"Space",
	guard_curse_of_the_machine	= 	"G",
	guard_incendiary_bombs		=	"Z",
	guard_emp_bombs			= 	"X",
	guard_smoke_bombs		= 	"C",
	guard_krak_bombs		= 	"B",

	-- ABILITIES FOR DARK ELDAR
	dark_eldar_animus_vitae			=	"E",
	dark_eldar_combat_drugs			=	"Z",
	dark_eldar_crucible			=	"X",
	dark_eldar_darklance_sweep		=	"Z",
	dark_eldar_execute_slave		=	"O",
	dark_eldar_gruesome_display		=	"Q",
	dark_eldar_talisman_of_petrification    = 	"O",
	dark_eldar_horrorfex			=	"F",
	dark_eldar_short_circuit		=  	"Z",
	dark_eldar_stinger			=  	"X",
	dark_eldar_tame_warp_beasts		=	"C",
	dark_eldar_terrorfex			=  	"C", 
	dark_eldar_torture_amp			=	"G",
	dark_eldar_wildfire			=	"R",
	dark_eldar_soul_shock			=	"Z",
	dark_eldar_tracking_device		=	"Z",
	dark_eldar_soul_destruction		=	"V",
	dark_eldar_haywire_bombs		=	"O",
	dark_eldar_war_frenzy			=	"O",
	dark_eldar_harvest_souls		=	"V",
	dark_eldar_piercing_vision		=	"I",
	dark_eldar_screams_of_the_damned	=	"O",
	dark_eldar_rend_soul			=	"T",
	dark_eldar_corrosion			=	"J",
	dark_eldar_rekindle_rage		=	"K",
	dark_eldar_soulstorm			=	"L",

	-- ABILITIES FOR SISTERS
	sisters_ascension			=	"R",
	sisters_divine_light			=	"V",
	sisters_divine_retribution		=	"F",
	sisters_emperors_touch			=	"J",
	sisters_holy_passion			=	"Z",
	sisters_ardent_flame			=	"X",
	sisters_battle_standard			=	"X",
	sisters_lay_hands			=	"I",
	sisters_conflagration			=	"G",
	sisters_hk_missiles			=	"Z",
	sisters_holy_rage			=	"O",
	sisters_krak_grenades			=	"C",
	sisters_mandate				=	"X",
	sisters_phosphor_grenades		=	"C",
	sisters_righteous_fervor		=	"H",
	sisters_seal_of_purity			=	"O",
	sisters_divine_pronouncement		=	"E",
	sisters_witch_hammer			=	"T", 
	sisters_worship				=	"O",
	sisters_rosarius			=	"O",
	sisters_laud_hailer			=	"N",
	sisters_angelic_visage			=	"Z",
	sisters_dismantle			=	"B",

	--Entity attack range
	attack					= 	"X",
	
	}

camera_bindings =
{
	----------------------------------------------------------------------------------------------------------------
	-- CAMERA COMMANDS
	----------------------------------------------------------------------------------------------------------------
	camera_panleft		= "A",
	camera_panright		= "D",
	camera_panup		= "W",
	camera_pandown		= "S",
	camera_rotate		= "Alt", 
	camera_defaultcam	= "Backspace",

	}
